# Configurações para os programas pre_processamento.py e analise_exploratoria_de_dados_eda.py

# Configuração de logging
logging:
  level: INFO
  filename: 'processamento_dados.log'
  format: '%(asctime)s:%(levelname)s:%(message)s'

# Configurações de dados
data:
  raw_file_path: 'D:\\Github\\data-science\\projetos\\analise-de-sentimentos\\nlp\\data\\raw\\asentimentos.parquet'
  processed_file_path: 'D:\\Github\\data-science\\projetos\\analise-de-sentimentos\\nlp\\data\\processed\\asentimentos_cleaned.parquet'
  processed: 'D:\\Github\\data-science\\projetos\\analise-de-sentimentos\\nlp\\data\\processed\\'
  final_file_path: 'D:\\Github\\data-science\\projetos\\analise-de-sentimentos\\nlp\\data\\processed\\final_asentiments.parquet'
  reports_dir: 'D:\\Github\\data-science\\projetos\\analise-de-sentimentos\\nlp\\reports\\'
  figures_dir: 'D:\\Github\\data-science\\projetos\\analise-de-sentimentos\\nlp\\reports\\figures\\'

# Configurações de limpeza de texto
text_cleaning:
  remove_urls: True
  remove_special_characters: True
  lowercase: True
  remove_stopwords: True
  demojize: True

# Configurações para análise exploratória
exploratory_analysis:
  top_n_words: 20
  top_n_hashtags: 20
  top_n_mentions: 20
  top_n_bigrams: 20
  top_n_trigrams: 20
  hist_bins: 30
  sentiment_count_figure: 'distribuicao_sentimentos.png'
  date_dist_figure: 'distribuicao_datas.png'
  top_hashtags_figure: 'top_20_hashtags.png'
  top_mentions_figure: 'top_20_mentions.png'
  top_bigrams_figure: 'top_20_bigrams.png'
  top_trigrams_figure: 'top_20_trigrams.png'
  sentiment_count_csv: 'sentiment_analysis.csv'
  sentiment_analysis_file: 'sentiment_analysis.parquet'