directories:
  logs: D:\Github\data-science\projetos\analise-de-sentimentos\nlp\logs
  processed_data: D:\Github\data-science\projetos\analise-de-sentimentos\nlp\data\processed\
  raw_data: D:\Github\data-science\projetos\analise-de-sentimentos\nlp\data\raw\
files:
  log_file: etapa2_6_vetorizacao_texto.log
  processed_dataset: etapa2_6_vetorizacao_texto.parquet
  processed_dataset_csv: etapa2_6_vetorizacao_texto.csv
  raw_dataset: asentimentos.parquet
